server:
  ip: localhost
  port: 9090
  tomcat:
    accesslog:
      enabled: true
      directory: ./logs
      prefix: access
      suffix: .log
      pattern: "%h %l %u %t \"%r\" %s %b \"%{Referer}i\" \"%{User-Agent}i\""
      file-date-format: yyyy-MM-dd
      rename-on-rotate: true
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/softwarecup?serverTimezone=GMT%2b8
    username: root
    password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
  servlet:
    multipart:
      max-file-size: 1500MB
      max-request-size: 1500MB

mybatis:
  mapper-locations: classpath:mapper/*.xml  #扫描所有mybatis的xml文件
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

files:
  upload:

    path: D:/code/Software-Cup/files/
  pythonupload:
    path: D:/code/Software-Cup/data/
  pythondownload:
    path: D:/code/Software-Cup/
  Jsondownload:
    path: D:/code/Software-Cup/json/
  pythonDataTestupload:
    path: D:/Software-Cup/OnlinePredict/
